### PR TITLE
Fixing handling of --drupalDistro CLI option as prompt override

### PR DESCRIPTION
**Pull request by arithmetric**
This fixes the first reason automated tests were failing. `--drupalDistro` wasn't working because when the prompt returns this option it returns a distro settings object, but only the text value was available when set via CLI option.

This resulted in the following error:

```
TypeError: undefined is not a function

    at module.exports.yeoman.generators.Base.extend.configuring.getDistroRelease (/home/travis/build/phase2/generator-gadget/app/index.js:54:28)
```

This also adds a run of grunt to the Travis test script.

Note: With the above error fixed, the automated tests now fail due to the processing of templates, which is addressed by #33 and #35.

### CODE REVIEW

**Comment by grayside** [comment]
Approved! I'd merge but github blocks mobile merging on failing branches now.
